### ISSUE TITLE
Add a CI System

### ISSUE THREAD

**Issue by szabgab** [shlomif/perl-Code-TidyAll-Plugin-Flake8#1]
It could help by running your tests on multiple platforms as soon as you push the changes to GitHub, long before they arrive to CPAN.

**Comment by shlomif** [comment]
@szabgab : I agree. can we use github actions and https://github.com/nektos/act ?

**Comment by shlomif** [comment]
Fixed in a recent commit: https://github.com/shlomif/perl-Code-TidyAll-Plugin-Flake8/commit/bd5c11b4d4660012d79782a901908bb5c8497aa1 . thanks!
